# spring.mandatory-file-encoding=UTF-8
spring:
    thymeleaf:
        cache: false
    output:
        ansi:
            enabled: ALWAYS
logging:
    charset:
        console: 866
    pattern:
        console: "%clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
        com.example: TRACE

filepaths:
    imageMagickHashFiles:
        E:\PHOTOS\Очень старые фотографии\очСтарImgHash 20230609.tsv,
        E:\PHOTOS\оцифрПлjpghash20230530.tsv,
        E:\PHOTOS\oldphjpghashlen20230211.tsv
    imageObjectsJson: C:\Users\user\imageObjects 20230609.json
    tagIdToNameFile: C:\Users\user\Documents\RelativesDates.txt
    thumbsDirectory: C:\users\user\thumbs\


#logging.level.org.springframework=DEBUG
#logging.level.org.springframework.core.io=TRACE
#logging.level.org.springframework.boot.context=TRACE