spring:
    thymeleaf:
        cache: false
    output:
        ansi:
            enabled: ALWAYS
    # neo4j:
    #     uri: bolt://localhost:7687
    #     authentication: 
    #         username: neo4j
    #         password: neo4j
            # password: 12345678

logging:
    charset:
        console: 866
    pattern:
        console: "%clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
        com.example: TRACE
        com.example.graphviz: INFO
        com.example.demo.ImageProvider: INFO
        com.example.demo.service.PersonService: INFO

filepaths:
    # dgkmRoot: E:\PHOTOS
    # imageMagickHashFiles:
    #     E:\PHOTOS\Очень старые фотографии\очСтарImgHash 20230609.tsv,
    #     E:\PHOTOS\оцифрПлjpghash20230530.tsv,
    #     E:\PHOTOS\oldphjpghashlen20230211.tsv
    # imageObjectsJson: C:\Users\user\imageObjects 20230609.json
    imageObjectsJson: classpath:sampleData\imageObjs.json
    # tagIdToNameFile: C:\Users\user\Documents\RelativesDates.txt
    # graphvizTree: C:\Users\user\Documents\FamilyTree Photos.txt
    graphvizTree: classpath:sampleData\familyTree.dot
    thumbsDirectory: C:\users\user\thumbs\
    # whiteListDirectories:
    #     E:\PHOTOS\Очень старые фотографии
        # E:\PHOTOS\Очень старые фотографии\скан2021
    # blackListDirectories: 
    #     E:\PHOTOS\Старые фотографии\Виталик,
        # E:\PHOTOS\iphone

# jdbc:
#     driverClassName: org.sqlite.JDBC
#     url: jdbc:sqlite:C:/Users/user/digikam4.db


  